[[quote]]
japanese = "逃げちゃダメだ"
translation = "You mustn't run away."
romaji = "Nigeccha dame da"
source = "Neon Genesis Evangelion"

[[quote]]
japanese = "人は心で生きるんだ"
translation = "People live by their hearts."
romaji = "Hito wa kokoro de ikiru nda"
source = "Your Name"

[[quote]]
japanese = "諦めたらそこで試合終了だよ"
translation = "If you give up, the game is over."
romaji = "Akirametara soko de shiai shūryō da yo"
source = "Slam Dunk"

[[quote]]
japanese = "人はいつ死ぬと思う？心の中で誰かに忘れられたときさ"
translation = "Do you know when people die? When they are forgotten in someone’s heart."
romaji = "Hito wa itsu shinu to omou? Kokoro no naka de dareka ni wasurerareta toki sa"
source = "One Piece"

[[quote]]
japanese = "心を燃やせ"
translation = "Set your heart ablaze."
romaji = "Kokoro o moyase"
source = "Tengen Toppa Gurren Lagann"

[[quote]]
japanese = "道は自分で切り開くものだ"
translation = "You carve your own path."
romaji = "Michi wa jibun de kirihiraku mono da"
source = "Naruto"

[[quote]]
japanese = "命より大事なものなんてない"
translation = "There’s nothing more important than life."
romaji = "Inochi yori daiji na mono nante nai"
source = "Fullmetal Alchemist"

[[quote]]
japanese = "俺の辞書に不可能はない"
translation = "Impossible doesn’t exist in my dictionary."
romaji = "Ore no jisho ni fukanō wa nai"
source = "One Piece"

[[quote]]
japanese = "人は信じたいものを信じる"
translation = "People believe what they want to believe."
romaji = "Hito wa shinjitai mono o shinjiru"
source = "Death Note"

# 10
[[quote]]
japanese = "夢を諦めるな"
translation = "Never give up on your dreams."
romaji = "Yume o akirameru na"
source = "Fairy Tail"

[[quote]]
japanese = "本当の強さとは優しさだ"
translation = "True strength is kindness."
romaji = "Hontō no tsuyosa to wa yasashisa da"
source = "Attack on Titan"

[[quote]]
japanese = "恐れずに進め"
translation = "Move forward without fear."
romaji = "Osorezu ni susume"
source = "My Hero Academia"

[[quote]]
japanese = "生きるってことは戦うことだ"
translation = "To live is to fight."
romaji = "Ikiru tte koto wa tatakau koto da"
source = "Bleach"

[[quote]]
japanese = "逃げ出した先に　楽園なんてありゃしねえのさ"
translation = "There is no paradise for you to escape to."
romaji = "nigedashita saki ni rakuen nante arya shinē nosa"
source = "Berserk"

[[quote]]
japanese = "アリを踏み潰すことを気にしてたら歩くこともできゃしねえんだ"
translation = "If you worry about stepping on ants, you won't be able to walk."
romaji = "ari o fumi tsubusu koto o ki ni shitetara aruku koto mo deki yashinēnda"
source = "Berserk"

[[quote]]
japanese = "誰のためでもない　自分が自分自身のために成す夢です "
translation = "It's a dream I achieve for myself, not for anyone else."
romaji = "dare no tame de mo nai jibun ga jibun jishin no tame ni nasu yumedesu"
source = "Berserk"

[[quote]]
japanese = "私にとって友とはそんな…”対等な者”だと思っています"
translation = "To me, a friend is someone who is an equal."
romaji = " watakushi ni totte tomo to wa sonna… ”taitō na mono” da to omotte imasu "
source = "Berserk"

[[quote]]
japanese = "あいつは自分自身をいつも極限まで研ぎ澄ましておかなければならないんだ"
translation = "One has to constantly push himself to the limits."
romaji = "aitsu wa jibun jishin o itsu mo kyokugen made togisumashite okanakere ba naranai n da "
source = "Berserk"

[[quote]]
japanese = "今やんねぇやつは！一生やりゃしねぇんだ！！"
translation = "If you don't do it now, you'll never do it in your life!!"
romaji = " ima yannei yatsu wa！ isshō yaryashinei n da !！"
source = "Berserk"

# 20
[[quote]]
japanese = "自分の手に負えないならケンカなんて仕掛けるんじゃないよ"
translation = "Don't start a fight if it's beyond your control."
romaji = "jibun no te ni oenainara kenka nante shikakeru n ja nai yo"
source = "Berserk"

[[quote]]
japanese = "光が強ければ強いほど濃い影が落ちるものさ"
translation = "The stronger the light, the darker the shadows."
romaji = " hikari ga tsuyokereba tsuyoi hodo koi kage ga ochiru monosa "
source = "Berserk"

[[quote]]
japanese = "憎しみってやつわな、悲しみに面と向かって腰を据えらんねえやつが逃げ込む場所だ"
translation = "Hatred is a place where those who can't stand facing sadness can escape."
romaji = "nikushimi tte yatsu wana , kanashimi ni men to mukatte koshi o sue ranne e yatsu ga nigekomu bashoda "
source = "Berserk"

[[quote]]
japanese = "絶対大丈夫だよ"
translation = "It’ll absolutely be okay."
romaji = "Zettai daijōbu da yo"
source = "Cardcaptor Sakura (Kinomoto Sakura)"

[[quote]]
japanese = "君はヒーローになれる"
translation = "You can become a hero."
romaji = "Kimi wa hīrō ni nareru"
source = "My Hero Academia (All Might)"

[[quote]]
japanese = "夢は大きく、欲は小さく。そういう気持ちで生きるようにしろ。"
translation = "Dream big, want little. Live with that kind of attitude."
romaji = "Yume wa ōkiku, yoku wa chiisaku. Sō iu kimochi de ikiru yō ni shiro"
source = "Chibi Maruko-chan"

[[quote]]
japanese = "命にかかわること以外どーでもいいことばっかり..."
translation = "Everything except life-threatening matters is no big deal..."
romaji = "Inochi ni kakawaru koto igai dō demo ii koto bakkari..."
source = "Chibi Maruko-chan"

[[quote]]
japanese = "怖い…自分の心に踏み込むのが怖い"
translation = "Scary... It's scary to step into my own heart."
romaji = "Kowai... jibun no kokoro ni fumikomu no ga kowai"
source = "Erased"

[[quote]]
japanese = "善行も悪行も本質は同じ、人が自らの欠陥を補う為の行いに過ぎない"
translation = "Good deeds and bad deeds are essentially the same, they're just actions people take to compensate for their own flaws."
romaji = "Zenkō mo akkō mo honshitsu wa onaji, hito ga mizukara no ketsujō o oginau tame no okonai ni suginai"
source = "Erased"

# 30
[[quote]]
japanese = "このヒトデナシ！"
translation = "You bastards!"
romaji = "Kono hitodenashi!"
source = "South Park"

[[quote]]
japanese = "認めたくないものだな。自分自身の若さ故の過ちというものを"
translation = "None want to admit them. The mistakes we make in our youth."
romaji = "Mitometakunai mono da na. Jibun jishin no wakasa yue no ayamachi to iu mono o"
source = "Mobile Suit Gundam" 

[[quote]]
japanese = "こいつ…うごくぞ！"
translation = "This thing... it moves!"
romaji = "Koitsu... ugoku zo!"
source = "Mobile Suit Gundam"

[[quote]]
japanese = "当たらなければどうという事はない！"
translation = "If it doesn't hit, it doesn't matter!"
romaji = "Ataranakereba dō to iu koto wa nai!"
source = "Mobile Suit Gundam"

[[quote]]
japanese = "二度もぶった。親父にもぶたれた事ないのに！"
translation = "You hit me twice! Even my father never hit me!"
romaji = "Nidō mo butta. Oyaji ni mo butareta koto nai no ni!"
source = "Mobile Suit Gundam"

[[quote]]
japanese = "ザクとは違うのだよ、ザクとは！"
translation = "This is no Zaku, boy! No Zaku!"
romaji = "Zaku to wa chigau no da yo, Zaku to wa!"
source = "Mobile Suit Gundam"

[[quote]]
japanese = "坊やだからさ"
translation = "Because [he was] a brat."
romaji = "Bōya da kara sa"
source = "Mobile Suit Gundam"

[[quote]]
japanese = "悲しいけどこれ戦争なのよね"
translation = "It's sad, but this is war."
romaji = "Kanashii kedo kore sensō nanoyone"
source = "Mobile Suit Gundam" 

[[quote]]
japanese = "ごめんよ、僕にはまだ帰れる所があるんだ"
translation = "I'm sorry, but I still have a home to return to."
romaji = "Gomen yo, boku ni wa mada kaereru tokoro ga arun da"
source = "Mobile Suit Gundam" 

# 40
[[quote]]
japanese = "あんなの飾りです、偉い人にはそれがわからんのですよ"
translation = "[Legs] are just for show. The higher-ups just don't get it."
romaji = "Anna no kazari desu, erai hito ni wa sore ga wakaran no desu yo"
source = "Mobile Suit Gundam"

[[quote]]
japanese = "俺がガンダムだ！"
translation = "I am Gundam!"
romaji = "Ore ga Gandamu da!"
source = "Mobile Suit Gundam 00"

[[quote]]
japanese = "逃げたら一つ、進めば二つ"
translation = "Run and gain one, move forward and gain two."
romaji = "Nigetara hitotsu, susumeba futatsu"
source = "Mobile Suit Gundam: The Witch from Mercury"

[[quote]]
japanese = "今日も一日がんばるぞい！"
translation = "I'll do my best today!"
romaji = "Kyō mo ichinichi ganbaru zoi!"
source = "New Game! (Suzukaze Aoba), anime ep. 4 / manga vol. 1"
