[[quote]]
japanese = "古池や\n蛙飛び込む\n水の音"
translation = "An old pond —\nA frog jumps in —\nThe sound of water."
romaji = "Furuike ya\nKawazu tobikomu\nMizu no oto"
source = "Matsuo Bashō"

[[quote]]
japanese = "夏草や\n兵どもが\n夢の跡"
translation = "Summer grasses—\nAll that remains\nOf warriors' dreams."
romaji = "Natsukusa ya\nTsuwamono-domo ga\nYume no ato"
source = "Matsuo Bashō"

[[quote]]
japanese = "静けさや\n岩にしみ入る\n蝉の声"
translation = "Such stillness—\nThe cicadas' cries\nSink into the rocks."
romaji = "Shizukesa ya\nIwa ni shimiiru\nSemi no koe"
source = "Matsuo Bashō"

[[quote]]
japanese = "春の海\nひねもすのたり\nのたりかな"
translation = "Spring sea—\nAll day long\nWaves roll gently."
romaji = "Haru no umi\nHinemosu notari\nNotari kana"
source = "Matsuo Bashō"

[[quote]]
japanese = "秋深き\n隣は何を\nする人ぞ"
translation = "Deep autumn—\nWho lives next door\nAnd what do they do?"
romaji = "Aki fukaki\nTonari wa nani o\nSuru hito zo"
source = "Matsuo Bashō"

[[quote]]
japanese = "冬ざれや\nかなしき鳥の\n声する"
translation = "Winter desolation—\nThe sad voice\nOf a bird."
romaji = "Fuyuzare ya\nKanashiki tori no\nKoe suru"
source = "Matsuo Bashō"

[[quote]]
japanese = "夏の夜や\n蛍の光\n消えたり"
translation = "Summer night—\nThe glow of fireflies\nFades away."
romaji = "Natsu no yo ya\nHotaru no hikari\nKietari"
source = "Matsuo Bashō"

[[quote]]
japanese = "花の雲\n鐘は上野か\n浅草か"
translation = "Clouds of blossoms—\nIs that bell from Ueno?\nOr from Asakusa?"
romaji = "Hana no kumo\nKane wa Ueno ka\nAsakusa ka"
source = "Matsuo Bashō"

[[quote]]
japanese = "春雨や\n川面を濡らす\n小舟かな"
translation = "Spring rain—\nIt wets the river’s surface,\nA little boat floats."
romaji = "Harusame ya\nKawamo o nurasu\nKobune kana"
source = "Matsuo Bashō"

# 10
[[quote]]
japanese = "朝顔に\nつるべ取られて\nもらい水"
translation = "Morning glory—\nMy well bucket was taken,\nGot water from neighbor."
romaji = "Asagao ni\nTsurube torarete\nMorai mizu"
source = "Kobayashi Issa"

[[quote]]
japanese = "名月や\n池をめぐりて\n夜もすがら"
translation = "Bright moon—\nAround the pond\nAll night long."
romaji = "Meigetsu ya\nIke o megurite\nYo mo sugara"
source = "Matsuo Bashō"

[[quote]]
japanese = "夏草や\n武士どもが\n夢の跡"
translation = "Summer grasses—\nAll that remains\nOf warriors’ dreams."
romaji = "Natsukusa ya\nBushidomo ga\nYume no ato"
source = "Matsuo Bashō"

[[quote]]
japanese = "春の山\n霞たなびく\n花の声"
translation = "Spring mountains—\nMist floats by,\nVoices of flowers."
romaji = "Haru no yama\nKasumi tanabiku\nHana no koe"
source = "Matsuo Bashō"

[[quote]]
japanese = "松島や\nああ松島や\n松島かな"
translation = "Matsushima! Ah, Matsushima! Matsushima?"
romaji = "Matsushima ya\nAa Matsushima ya\nMatsushima kana"
source = "Tawara Bo"

[[quote]]
japanese = "荒海や\n佐渡に横たふ\n天の川"
translation = "Rough sea—\nStretching across to Sado,\nThe Milky Way."
romaji = "Araumi ya\nSado ni yokotau\nAmanogawa"
source = "Matsuo Bashō"

[[quote]]
japanese = "菜の花や\n月は東に\n日は西に"
translation = "Rapeseed blossoms—\nThe moon in the east,\nThe sun in the west."
romaji = "Nanohana ya\nTsuki wa higashi ni\nHi wa nishi ni"
source = "Yosa Buson"

[[quote]]
japanese = "五月雨を\nあつめて早し\n最上川"
translation = "Gathering the rains—\nSwift is the flow\nOf the Mogami River."
romaji = "Samidare o\nAtsumete hayashi\nMogamigawa"
source = "Matsuo Bashō"

[[quote]]
japanese = "おもしろき\nこともなき世を\nおもしろく"
translation = "A world of nothing—\nYet I make it\nFull of wonder."
romaji = "Omosoroki\nKoto mo naki yo o\nOmosoroku"
source = "Takarai Kikaku"