# Bad Apple!! feat. Nomico. Lyrics from Touhou Wiki
[[quote]]
japanese = "流(なが)れてく　時(とき)の中(なか)ででも　気(け)だるさが　ほらグルグル廻(まわ)って"
translation = "Even in the midst of flowing time, I feel languid, look, spinning around and around"
romaji = "Nagareteku toki no naka de demo kedarusa ga hora guruguru mawatte"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "私(わたし)から　離(はな)れる心(こころ)も　見(み)えないわ　そう知(し)らない？"
translation = "I can't even see the heart that's leaving me, didn't you know?"
romaji = "Watashi kara hanareru kokoro mo mienaiwa sou shiranai?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "自分(じぶん)から　動(うご)くこともなく　時(とき)の隙間(すきま)に　流(なが)され続(つづ)けて"
translation = "I can't even get myself to move, I continue to be washed down the cracks of time"
romaji = "Jibun kara ugoku koto mo naku toki no sukima ni nagasare tsuzukete"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "知(し)らないわ　周(まわ)りのことなど　私(わたし)は私(わたし)　それだけ"
translation = "I don't know anything about what's around me, I'm just me and no more"
romaji = "Shiranai wa mawari no koto nado watashi wa watashi sore dake"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "夢(ゆめ)見(み)てる？　なにも見(み)てない？　語(かた)るも無駄(むだ)な　自分(じぶん)の言葉(ことば)"
translation = "Am I dreaming? Or seeing nothing? My words are useless even if I speak"
romaji = "Yume miteru? Nani mo mitenai? Kataru mo muda na jibun no kotoba"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "悲(かな)しむなんて　疲(つか)れるだけよ　何(なに)も感(かん)じず　過(す)ごせばいいの"
translation = "I'm just tired of being sad, I should go on without feeling anything"
romaji = "Kanashimu nante tsukareru dake yo nani mo kanjizu sugoseba ii no"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "戸惑(とまど)う言葉(ことば)　与(あた)えられっても　自分(じぶん)の心(こころ)　ただ上(うわ)の空(そら)"
translation = "Even if you give me the words I'm at a loss for, my heart just won't pay attention"
romaji = "Tomadou kotoba ataerarete mo jibun no kokoro tada uwa no sora"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "もし私(わたし)から　動(うご)くのならば　すべて変(か)えるのなら　黒(くろ)にする"
translation = "If I move myself away, if I change everything, I'll turn it all black"
romaji = "Moshi watashi kara ugoku no naraba subete kaeru no nara kuro ni suru"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "こんな自分(じぶん)に　未来(みらい)はあるの？　こんな世界(せかい)に　私(わたし)はいるの？"
translation = "Is there a future for someone like me? Will I still exist in a world like this?"
romaji = "Konna jibun ni mirai wa aru no? Konna sekai ni watashi wa iru no?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "今(いま)切(せつ)ないの？　今(いま)悲(かな)しいの？　自分(じぶん)の事(こと)も　わからないまま"
translation = "Is this painful? Is it sad? Not even knowing myself"
romaji = "Ima setsunai no? Ima kanashii no? Jibun no koto mo wakaranai mama"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "歩(あゆ)むことさえ　疲(つか)れるだけよ　人(ひと)のことなど　知(し)りもしないわ"
translation = "I'm just tired even of walking, I don't even understand people."
romaji = "Ayumu koto sae tsukareru dake yo hito no koto nado shiri mo shinaiwa"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "こんな私(わたし)も　変(かわ)われるのなら　もし変(かわ)われるのなら　白(しろ)になる"
translation = "If someone like me can change, if I can change, will I turn white?"
romaji = "Konna watashi mo kawareru no nara moshi kawareru no nara shiro ni naru"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "無駄(むだ)な時間(じかん)に　未来(みらい)はあるの？　こんな所(とこ)に　私(わたし)はいるの？"
translation = "Is there a future to come out of this useless time? Will I exist in a place like this?"
romaji = "Muda na jikan ni mirai wa aru no? Konna tokoro ni watashi wa iru no?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "私(わたし)のことを　言(い)いたいならば　ことばにするのなら　「ろくでなし」"
translation = "If I wanted to tell you what kind of person I am, the words I'd use would be 'good for nothing'"
romaji = "Watashi no koto wo iitai naraba kotoba ni suru no nara [rokudenashi]"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "今(いま)夢(ゆめ)見(み)てる？　なにも見(み)てない？　語(かた)るも無駄(むだ)な　自分(じぶん)の言葉(ことば)"
translation = "Am I dreaming now? Or seeing nothing? My words are useless even if I speak"
romaji = "Ima yume miteru? Nani mo mitenai? Kataru mo muda na jibun no kotoba"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "動(うご)くのならば　動(うご)くのならば　すべて壊(こわ)すわ　すべて壊(こわ)すわ"
translation = "If I move, if I move, I'll destroy everything, I'll destroy everything"
romaji = "Ugoku no naraba ugoku no naraba subete kowasuwa subete kowasuwa"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "悲(かな)しむならば　悲(かな)しむならば　私(わたし)の心(こころ)　白(しろ)く変(かわ)われる？"
translation = "If I grieve, if I grieve, can my heart turn white?"
romaji = "Kanashimu naraba kanashimu naraba watashi no kokoro shiroku kawareru?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "貴方(あなた)の事(こと)も　私(わたし)のことも　全(すべ)ての事(こと)も　まだ知(し)らないの"
translation = "I still don't know about you, about myself, about everything"
romaji = "Anata no koto mo watashi no koto mo subete no koto mo mada shiranai no"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "重(おも)い目蓋(まぶた)を　開(あ)けたのならば　すべて壊(こわ)すのなら　黒(くろ)になれ！！！"
translation = "If I can open my heavy eyelids, if I break everything, then turn black！！！"
romaji = "Omoi mabuta wo aketa no naraba subete kowasu no nara kuro ni nare！！！"
source = "Bad Apple!! (Alstroemeria Records)"
