# multiple songs can coexist here ^_^
# Bad Apple!! (Alstroemeria Records)

[[quote]]
japanese = "流れてく　時の中ででも　気だるさが　ほらグルグル廻って"
translation = "Even in the midst of flowing time, I feel languid, look, spinning around and around"
romaji = "Nagareteku toki no naka de demo kedarusa ga hora guruguru mawatte"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "私から　離れる心も　見えないわ　そう知らない？"
translation = "I can't even see the heart that's leaving me, didn't you know?"
romaji = "Watashi kara hanareru kokoro mo mienaiwa sou shiranai?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "自分から　動くこともなく　時の隙間に　流され続けて"
translation = "I can't even get myself to move, I continue to be washed down the cracks of time"
romaji = "Jibun kara ugoku koto mo naku toki no sukima ni nagasare tsuzukete"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "知らないわ　周りのことなど　私は私　それだけ"
translation = "I don't know anything about what's around me, I'm just me and no more"
romaji = "Shiranai wa mawari no koto nado watashi wa watashi sore dake"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "夢見てる？　なにも見てない？　語るも無駄な　自分の言葉"
translation = "Am I dreaming? Or seeing nothing? My words are useless even if I speak"
romaji = "Yume miteru? Nani mo mitenai? Kataru mo muda na jibun no kotoba"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "悲しむなんて　疲れるだけよ　何も感じず　過ごせばいいの"
translation = "I'm just tired of being sad, I should go on without feeling anything"
romaji = "Kanashimu nante tsukareru dake yo nani mo kanjizu sugoseba ii no"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "戸惑う言葉　与えられても　自分の心　ただ上の空"
translation = "Even if you give me the words I'm at a loss for, my heart just won't pay attention"
romaji = "Tomadou kotoba ataerarete mo jibun no kokoro tada uwa no sora"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "もし私から　動くのならば　すべて変えるのなら　黒にする"
translation = "If I move myself away, if I change everything, I'll turn it all black"
romaji = "Moshi watashi kara ugoku no naraba subete kaeru no nara kuro ni suru"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "こんな自分に　未来はあるの？　こんな世界に　私はいるの？"
translation = "Is there a future for someone like me? Will I still exist in a world like this?"
romaji = "Konna jibun ni mirai wa aru no? Konna sekai ni watashi wa iru no?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "今切ないの？　今悲しいの？　自分の事も　わからないまま"
translation = "Is this painful? Is it sad? Not even knowing myself"
romaji = "Ima setsunai no? Ima kanashii no? Jibun no koto mo wakaranai mama"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "歩むことさえ　疲れるだけよ　人のことなど　知りもしないわ"
translation = "I'm just tired even of walking, I don't even understand people."
romaji = "Ayumu koto sae tsukareru dake yo hito no koto nado shiri mo shinaiwa"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "こんな私も　変われるのなら　もし変われるのなら　白になる"
translation = "If someone like me can change, if I can change, will I turn white?"
romaji = "Konna watashi mo kawareru no nara moshi kawareru no nara shiro ni naru"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "無駄な時間に　未来はあるの？　こんな所に　私はいるの？"
translation = "Is there a future to come out of this useless time? Will I exist in a place like this?"
romaji = "Muda na jikan ni mirai wa aru no? Konna tokoro ni watashi wa iru no?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "私のことを　言いたいならば　ことばにするのなら　「ろくでなし」"
translation = "If I wanted to tell you what kind of person I am, the words I'd use would be 'good for nothing'"
romaji = "Watashi no koto wo iitai naraba kotoba ni suru no nara [rokudenashi]"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "今夢見てる？　なにも見てない？　語るも無駄な　自分の言葉"
translation = "Am I dreaming now? Or seeing nothing? My words are useless even if I speak"
romaji = "Ima yume miteru? Nani mo mitenai? Kataru mo muda na jibun no kotoba"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "動くのならば　動くのならば　すべて壊すわ　すべて壊すわ"
translation = "If I move, if I move, I'll destroy everything, I'll destroy everything"
romaji = "Ugoku no naraba ugoku no naraba subete kowasuwa subete kowasuwa"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "悲しむならば　悲しむならば　私の心　白く変われる？"
translation = "If I grieve, if I grieve, can my heart turn white?"
romaji = "Kanashimu naraba kanashimu naraba watashi no kokoro shiroku kawareru?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "貴方の事も　私のことも　全ての事も　まだ知らないの"
translation = "I still don't know about you, about myself, about everything"
romaji = "Anata no koto mo watashi no koto mo subete no koto mo mada shiranai no"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "重い目蓋を　開けたのならば　すべて壊すのなら　黒になれ！！！"
translation = "If I can open my heavy eyelids, if I break everything, then turn black!!!"
romaji = "Omoi mabuta wo aketa no naraba subete kowasu no nara kuro ni nare!!!"
source = "Bad Apple!! (Alstroemeria Records)"
