# Bad Apple!! feat. Nomico. Lyrics from Touhou Wiki
[[quote]]
japanese = "流(なが)れてく　時(とき)の中(なか)ででも　気(け)だるさが　ほらグルグル廻(まわ)って"
translation = "Even in the midst of flowing time, I feel languid, look, spinning around and around"
romaji = "Nagareteku toki no naka de demo kedarusa ga hora guruguru mawatte"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "私(わたし)から　離(はな)れる心(こころ)も　見(み)えないわ　そう知(し)らない？"
translation = "I can't even see the heart that's leaving me, didn't you know?"
romaji = "Watashi kara hanareru kokoro mo mienaiwa sou shiranai?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "自分(じぶん)から　動(うご)くこともなく　時(とき)の隙間(すきま)に　流(なが)され続(つづ)けて"
translation = "I can't even get myself to move, I continue to be washed down the cracks of time"
romaji = "Jibun kara ugoku koto mo naku toki no sukima ni nagasare tsuzukete"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "知(し)らないわ　周(まわ)りのことなど　私(わたし)は私(わたし)　それだけ"
translation = "I don't know anything about what's around me, I'm just me and no more"
romaji = "Shiranai wa mawari no koto nado watashi wa watashi sore dake"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "夢(ゆめ)見(み)てる？　なにも見(み)てない？　語(かた)るも無駄(むだ)な　自分(じぶん)の言葉(ことば)"
translation = "Am I dreaming? Or seeing nothing? My words are useless even if I speak"
romaji = "Yume miteru? Nani mo mitenai? Kataru mo muda na jibun no kotoba"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "悲(かな)しむなんて　疲(つか)れるだけよ　何(なに)も感(かん)じず　過(す)ごせばいいの"
translation = "I'm just tired of being sad, I should go on without feeling anything"
romaji = "Kanashimu nante tsukareru dake yo nani mo kanjizu sugoseba ii no"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "戸惑(とまど)う言葉(ことば)　与(あた)えられっても　自分(じぶん)の心(こころ)　ただ上(うわ)の空(そら)"
translation = "Even if you give me the words I'm at a loss for, my heart just won't pay attention"
romaji = "Tomadou kotoba ataerarete mo jibun no kokoro tada uwa no sora"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "もし私(わたし)から　動(うご)くのならば　すべて変(か)えるのなら　黒(くろ)にする"
translation = "If I move myself away, if I change everything, I'll turn it all black"
romaji = "Moshi watashi kara ugoku no naraba subete kaeru no nara kuro ni suru"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "こんな自分(じぶん)に　未来(みらい)はあるの？　こんな世界(せかい)に　私(わたし)はいるの？"
translation = "Is there a future for someone like me? Will I still exist in a world like this?"
romaji = "Konna jibun ni mirai wa aru no? Konna sekai ni watashi wa iru no?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "今(いま)切(せつ)ないの？　今(いま)悲(かな)しいの？　自分(じぶん)の事(こと)も　わからないまま"
translation = "Is this painful? Is it sad? Not even knowing myself"
romaji = "Ima setsunai no? Ima kanashii no? Jibun no koto mo wakaranai mama"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "歩(あゆ)むことさえ　疲(つか)れるだけよ　人(ひと)のことなど　知(し)りもしないわ"
translation = "I'm just tired even of walking, I don't even understand people."
romaji = "Ayumu koto sae tsukareru dake yo hito no koto nado shiri mo shinaiwa"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "こんな私(わたし)も　変(かわ)われるのなら　もし変(かわ)われるのなら　白(しろ)になる"
translation = "If someone like me can change, if I can change, will I turn white?"
romaji = "Konna watashi mo kawareru no nara moshi kawareru no nara shiro ni naru"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "無駄(むだ)な時間(じかん)に　未来(みらい)はあるの？　こんな所(とこ)に　私(わたし)はいるの？"
translation = "Is there a future to come out of this useless time? Will I exist in a place like this?"
romaji = "Muda na jikan ni mirai wa aru no? Konna tokoro ni watashi wa iru no?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "私(わたし)のことを　言(い)いたいならば　ことばにするのなら　「ろくでなし」"
translation = "If I wanted to tell you what kind of person I am, the words I'd use would be 'good for nothing'"
romaji = "Watashi no koto wo iitai naraba kotoba ni suru no nara [rokudenashi]"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "今(いま)夢(ゆめ)見(み)てる？　なにも見(み)てない？　語(かた)るも無駄(むだ)な　自分(じぶん)の言葉(ことば)"
translation = "Am I dreaming now? Or seeing nothing? My words are useless even if I speak"
romaji = "Ima yume miteru? Nani mo mitenai? Kataru mo muda na jibun no kotoba"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "動(うご)くのならば　動(うご)くのならば　すべて壊(こわ)すわ　すべて壊(こわ)すわ"
translation = "If I move, if I move, I'll destroy everything, I'll destroy everything"
romaji = "Ugoku no naraba ugoku no naraba subete kowasuwa subete kowasuwa"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "悲(かな)しむならば　悲(かな)しむならば　私(わたし)の心(こころ)　白(しろ)く変(かわ)われる？"
translation = "If I grieve, if I grieve, can my heart turn white?"
romaji = "Kanashimu naraba kanashimu naraba watashi no kokoro shiroku kawareru?"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "貴方(あなた)の事(こと)も　私(わたし)のことも　全(すべ)ての事(こと)も　まだ知(し)らないの"
translation = "I still don't know about you, about myself, about everything"
romaji = "Anata no koto mo watashi no koto mo subete no koto mo mada shiranai no"
source = "Bad Apple!! (Alstroemeria Records)"

[[quote]]
japanese = "重(おも)い目蓋(まぶた)を　開(あ)けたのならば　すべて壊(こわ)すのなら　黒(くろ)になれ！！！"
translation = "If I can open my heavy eyelids, if I break everything, then turn black！！！"
romaji = "Omoi mabuta wo aketa no naraba subete kowasu no nara kuro ni nare！！！"
source = "Bad Apple!! (Alstroemeria Records)"

# 千本桜, lyrics from Vocaloid Lyrics Wiki, translation by Firingsniper
[[quote]]
japanese = "大胆不敵(だいたんふてき)にハイカラ革命(かくめい)"
translation = "Bold and fearless, a white-collared revolution"
romaji = "Daitanfuteki ni haikara kakumei"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "磊々落々(らいらいらくらく)反戦国家(はんせんこっか)"
translation = "Forbearing and rustic - a pacifist regime"
romaji = "Rairairakuraku hansen kokka"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "日(ひ)の丸(まる)印(じるし)の二輪車(にりんしゃ)転(ころ)がし"
translation = "Rolling two-wheels, with a crest of the Rising Sun"
romaji = "Hinomarujirushi no nirinsha korogashi"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "悪霊退散(あくりょうたいさん)　ICBM"
translation = "Begone, evil spirits - ICBM"
romaji = "Akuryoutaisan ICBM"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "環状線(かんじょうせん)を走(はし)り抜(ぬ)けて"
translation = "Through the peripheral lines, darting and dashing"
romaji = "Kanjousen o hashirinukete"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "東奔西走(とうほんせいそう)なんのその"
translation = "Hurriedly toiling about, no big deal"
romaji = "Touhonseisou nan no sono"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "少年少女(しょうねんしょうじょ)戦国無双(せんごくむそう)"
translation = "Young men and women, unmatched among warmongers"
romaji = "Shounen shoujo sengokumusou"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "浮世(うきよ)の随(まにま)に"
translation = "As our fleeting world dictates"
romaji = "Ukiyo no manima ni"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "千本桜(せんぼんざくら)　夜(よる)ニ紛(まぎ)レ"
translation = "Sakuras thousandfold, entwined with night"
romaji = "Senbonzakura yoru ni magire"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "君(きみ)ノ声(こえ)モ届(とど)カナイヨ"
translation = "Even your voice, shall not reach here"
romaji = "Kimi no koe mo todokanai yo"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "此処(ここ)は宴(うたげ)　鋼(はがね)の檻(おり)"
translation = "Herein rages a feast, a cage of steel"
romaji = "Koko wa utage hagane no ori"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "その断頭台(だんとうだい)で見下(みお)ろして"
translation = "From that guillotine, looking down upon"
romaji = "Sono dantoudai de mioroshite"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "三千世界(さんぜんせかい)　常世(とこよ)之(の)闇(やみ)"
translation = "A transcendent universe, gloom of the empyrean"
romaji = "Sanzen sekai tokoyo no yami"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "嘆(なげ)ク唄(うた)モ聞(き)コエナイヨ"
translation = "Even the lamenting songs, shall not be heard"
romaji = "Nageku uta mo kikoenai yo"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "青藍(せいらん)の空(そら)　遥(はる)か彼方(かなた)"
translation = "The indigo skies, lies faraway yonder"
romaji = "Seiran no sora haruka kanata"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "その光線銃(こうせんじゅう)で打(う)ち抜(ぬ)いて"
translation = "With that ray gun, impale the azures!"
romaji = "Sono kousenjuu de uchinuite"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "百戦錬磨(ひゃくせんれんま)の見(み)た目(め)は将校(しょうこう)"
translation = "The battle-hardened, veiled as an officer"
romaji = "Hyakusenrenma no mitame wa shoukou"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "いったりきたりの花魁(おいらん)道中(どうちゅう)"
translation = "Loitering about with courtesans, truly a wanderlust"
romaji = "Ittarikitari no oiran douchuu"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "アイツもコイツも皆(みな)で集(あつ)まれ"
translation = "That guy, this guy, everybody round up"
romaji = "Aitsu mo koitsu mo minna de atsumare"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "聖者(せいじゃ)の行進(こうしん)　わんっ　つー　さん　しっ"
translation = "The Saints' march - one, two, three, four"
romaji = "Seija no koushin wan tsuu san shi"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "禅定門(ぜんじょうもん)を潜(くぐ)り抜(ぬ)けて"
translation = "Passing through under the Zen gate"
romaji = "Zenjoumon o kugurinukete"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "安楽浄土(あんらくじょうど)厄払(やくばら)い"
translation = "The blissful lands, driving out evils"
romaji = "Anrakujoudo yakubarai"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "きっと終幕(さいご)は大団円(だいだんえん)"
translation = "Surely the finale will be laded with happiness"
romaji = "Kitto saigo wa daidanen"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "拍手(はくしゅ)の合間(あいま)に"
translation = "In-between the applauding,"
romaji = "Hakushu no aima ni"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "希望(きぼう)の丘(おか)　遥(はる)か彼方(かなた)"
translation = "The hills of hope, lies faraway yonder"
romaji = "Kibou no oka haruka kanata"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "その閃光弾(せんこうだん)を打(う)ち上(あ)げろ"
translation = "With that flash grenade, signal the skies!"
romaji = "Sono senkoudan o uchiagero"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "その断頭台(だんとうだい)を飛(と)び降(お)りて"
translation = "From that guillotine, jumping right off!"
romaji = "Sono dantoudai o tobiorite"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "君(きみ)が歌(うた)い僕(ぼく)は踊(おど)る"
translation = "You shall sing, and I shall dance"
romaji = "Kimi ga utai boku wa odoru"
source = "千本桜 (Whiteflame)"

[[quote]]
japanese = "さあ光線銃(こうせんじゅう)を撃(う)ちまくれ"
translation = "Here, with the raygun, do go ballistic"
romaji = "Saa kousenjuu o uchimakure"
source = "千本桜 (Whiteflame)"
