# some of these may be considered proverbs, but since they are standardised
# I thought it would be best toi seperate them.

[[quote]]
japanese = "起死回生"
translation = "Rise death return life - Revival"
romaji = "ki shi kai sei"
source = "四字熟語 - yojijukugo"