# some of these may be considered proverbs, but since they are standardised
# I thought it would be best toi seperate them.

[[quote]]
japanese = "起死回生"
translation = "Rise [from] death return [to] life"
romaji = "ki shi kai sei"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一石二鳥"
translation = "One stone, two birds"
romaji = "i sseki ni chō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "花鳥風月"
translation = "Flower bird wind moon - Nature's beauty"
romaji = "ka chō fū getsu"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "無我夢中"
translation = "No self, dream center - Absorption"
romaji = "mu ga mu chū"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "四苦八苦"
translation = "Four sufferings, eight sufferings - Great difficulty"
romaji = "shi ku ha kku"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "五里霧中"
translation = "Five leagues in fog - Completely lost"
romaji = "go ri mu chū"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "九死一生"
translation = "Nine deaths, one life - Narrow escape"
romaji = "kyū shi i sshō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "十人十色"
translation = "Ten people, ten colors - To each their own"
romaji = "jū nin to iro"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "百戦錬磨"
translation = "[A] hundred battles, polished [by]"
romaji = "hyaku sen ren ma"
source = "四字熟語 - yojijukugo"

# 10
[[quote]]
japanese = "千変万化"
translation = "[A] thousand changes, ten-thousand transformations"
romaji = "sen ben ban ka"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一攫千金"
translation = "One grab, [a] thousand gold - Fortune overnight"
romaji = "i kkaku sen kin"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一挙両得"
translation = "One action, two gains"
romaji = "i kkyo ryō toku"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一刀両断"
translation = "One sword, two cuts"
romaji = "i ttō ryō dan"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一気呵成"
translation = "One breath, completion"
romaji = "i kki ka sei"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一蓮托生"
translation = "One lotus, entrusted life - In the same boat"
romaji = "ichi ren taku shō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一心専意"
translation = "One heart, devoted intention"
romaji = "i sshin sen -i"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一見鍾情"
translation = "One look, affection - Love at first sight"
romaji = "i kken shō jō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一触即発"
translation = "One touch, immediate explosion"
romaji = "i ssoku ki hatsu"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "二律背反"
translation = "Two laws [in] contradiction"
romaji = "ni ritsu hai han"
source = "四字熟語 - yojijukugo"

# 20
[[quote]]
japanese = "三顧の礼"
translation = "Three visits in ceremony - Respet for talent"
romaji = "san ko no rei"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "六根清浄"
translation = "Six roots pure [and] clean - Free from the worldly desires"
romaji = "roku kon jō jō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "八面六臂"
translation = "Eight faces, six arms - Extraordinarily capable"
romaji = "ha ppō roku hi"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "万死一生"
translation = "Ten-thousand deaths, one life - Narrow escape"
romaji = "ban shi i sshō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一寸光明"
translation = "One lengh bright light - Glimmer of hope"
romaji = "i ssun kō myō"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一芸必達"
translation = "One art must reach - Mastery"
romaji = "ichi ge hitsu tatsu"
source = "四字熟語 - yojijukugo"

[[quote]]
japanese = "一念発起"
translation = "One thought rises, [one] starts - Resolution"
romaji = "ichi nen ha kkī"
source = "四字熟語 - yojijukugo"